# Numpy arrays 

In [1]:
import numpy as np 

In [3]:
list = [1,2,3,4,5]

arr = np.array(list)  #array fucntion creates an array based upon the given data type of array

arr #will print a 1D array 

array([1, 2, 3, 4, 5])

In [5]:
arr.shape #how many number of rows and columns are there

(5,)

# Converting 1D to 2D array 

In [76]:
list1 = [1,2,3,4,6,4]
list2 = [9,3,5,6,7,8]
list3 = [0,4,6,9,2,3]

arr = np.array([list1, list2, list3], dtype=object) #makind 2D arrays
arr

#if 2 square brackets a 2D array is made and if 3 square brackets 3D array

array([[1, 2, 3, 4, 6, 4],
       [9, 3, 5, 6, 7, 8],
       [0, 4, 6, 9, 2, 3]], dtype=object)

In [77]:
arr.shape

(3, 6)

In [80]:
arr.reshape(6,3) #will convert the total no of elements which should be the same into a new shape

array([[1, 2, 3],
       [4, 6, 4],
       [9, 3, 5],
       [6, 7, 8],
       [0, 4, 6],
       [9, 2, 3]], dtype=object)

In [38]:
arr.reshape(1,18) #since we have total elements 18 so we can only convert these 18 elements otherwise the array other than this will raise an error

array([[1, 2, 3, 4, 6, 4, 9, 3, 5, 6, 7, 8, 0, 4, 6, 9, 2, 3]],
      dtype=object)

# Indexing for 1D array

In [5]:
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = [7,8,9]

arr = np.array([arr1, arr2, arr3], dtype=object)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=object)

In [7]:
arr[1:,1:]

array([[5, 6],
       [8, 9]], dtype=object)

In [40]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [41]:
arr[0] #accessing element at index 0

1

# Indexing for 2D array 

In [67]:
arr

array([   1.        ,    1.18367347,    1.36734694, 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        , 1000.        , 1000.        ,
       1000.        , 1000.        ])

In [45]:
arr[:,:] #to print all the rows and all the columns

array([[1, 2, 3, 4, 6, 4],
       [9, 3, 5, 6, 7, 8],
       [0, 4, 6, 9, 2, 3]], dtype=object)

In [46]:
arr[0:2,:] #to get elements till the second row but get all the columns

array([[1, 2, 3, 4, 6, 4],
       [9, 3, 5, 6, 7, 8]], dtype=object)

In [47]:
arr[0:2,0:2] #to get the rows till index two and get column till index 2

array([[1, 2],
       [9, 3]], dtype=object)

In [48]:
arr[1:,3:]

array([[6, 7, 8],
       [9, 2, 3]], dtype=object)

# In-built Array Functions

In [52]:
arr = np.arange(0,10,step=2) # quickly creates a NEW 1D array ranging from 1 to 10 with an interval of 2 
arr

array([0, 2, 4, 6, 8])

In [54]:
arr = np.linspace(1,10,50) #to generate equally spaced 50 points in an array ranging from 1 to 10
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [56]:
#copy function and broadcasting

arr[3:]=100  #to replace the numbers startimg from index 3 up till the end with 100 
arr

array([  1.        ,   1.18367347,   1.36734694, 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        ])

In [58]:
#array reference typing is that the arrays are sharing the same memory block hence when there are two variables in the same memory block then change in one variable will result in changing of all variables to avoid this we can use the copy function 

arr1=arr
arr1[3:]=500
arr1

array([  1.        ,   1.18367347,   1.36734694, 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        ])

In [59]:
# a copy function creates a seperate memory block for storing the different variable

print(arr)
arr1[3:]=1000
print(arr1)

[  1.           1.18367347   1.36734694 500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.        ]
[   1.            1.18367347    1.36734694 1000.         1000.
 1000.         1000.         1000.         1000.         1000.
 1000.         1000.         1000.         1000.         1000.
 1000.         1000.         1000.         1000.         1000.
 1000.         1000.         1000.         1000.         1000.
 1000.         1000.         1000.         1000.         1000.
 1000.         1000.         1000

In [73]:
arr1 = np.arange(5,10).reshape(5)
arr1

array([5, 6, 7, 8, 9])

In [81]:
np.ones(4) #to convert the 4 elements of array to 1 only

array([1., 1., 1., 1.])

In [85]:
np.random.rand(3,3) #to generate random values of 3 rows and 3 columns in a uniform distribution 

array([[0.99496785, 0.55729562, 0.95140427],
       [0.55112869, 0.20655418, 0.3772287 ],
       [0.31737698, 0.68416219, 0.19132771]])

In [86]:
np.random.randn(4,4) #to generate random values in a standard normal distribution

array([[-0.51800968, -1.16589505, -1.41249714, -0.60479552],
       [-1.87185105, -0.46740063, -0.10239274, -0.50859849],
       [-0.52053677,  0.77452172, -1.45915453, -0.17865804],
       [-0.6746137 ,  1.51618104, -1.51122833, -0.03114089]])

In [94]:
np.random.randint(0,100,8).reshape(2,4) #also reshape to 2 rows and 4 columns #generate 8 random numbers between 0 to 100 

array([[32, 52, 56, 45],
       [53,  4, 85, 72]])

# Conditions useful for EDA

In [9]:
arr[arr<2] #to check for elements in the array which are less than 2

array([1], dtype=object)

In [10]:
arr<2

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [68]:
arr*2  #to multiply every every element with 2 in array

array([   2.        ,    2.36734694,    2.73469388, 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        , 2000.        , 2000.        ,
       2000.        , 2000.        ])